--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/CommandHelper
build-by-default: true
branches:
- master
projects:
  CommandHelper:
    path: ""
    lint: false
    libs:
      - src: sky-min/EventAttribute/EventAttribute
        version: ^2.0.0
...
